export default {
  "index": "Integrations",
  "claude-code": "Claude Code Configuration",
  "codex": "Codex Local Client Setup",
  "gemini-cli": "Gemini CLI Setup",
  "cursor": "Cursor Compatibility Notice",
  "copilot": "GitHub Copilot Configuration",
  "cline": "Cline Configuration",
  "openclaw": "OpenClaw",
  "cherry-studio": "Cherry Studio Configuration",
  "cc-switch": "CC-Switch Configuration",
  "botgem": "BotGem Setup",
  "chatbox": "Chatbox Configuration",
  "workbuddy": "WorkBuddy Configuration",
  "lobehub": "LobeHub Setup",
  "opencat": "OpenCat Setup",
  "nextchat": "NextChat Setup",
  "immersive-translate": "Immersive Translate Setup",
  "opencode": "OpenCode Configuration",
  "openai-sdk": "OpenAI SDK Compatible",
  "langchain": "LangChain Configuration",
  "llamaindex": "LlamaIndex Configuration",
  "others": "Other Integrations",
  "zed": "Zed Editor with Look2Eye Setup Guide",
}
