export default {
  "index": "Integrations",
  "claude-code": "Claude Code Configuration",
  "claude-desktop": "Claude Desktop Setup",
  "codex": "Codex Local Client Setup",
  "botgem": { display: 'hidden' },
  "cc-switch": { display: 'hidden' },
  "chatbox": { display: 'hidden' },
  "cherry-studio": { display: 'hidden' },
  "claude-coworks": { display: 'hidden' },
  "cline": { display: 'hidden' },
  "copilot": { display: 'hidden' },
  "cursor": { display: 'hidden' },
  "gemini-cli": { display: 'hidden' },
  "immersive-translate": { display: 'hidden' },
  "langchain": { display: 'hidden' },
  "llamaindex": { display: 'hidden' },
  "lobehub": { display: 'hidden' },
  "nextchat": { display: 'hidden' },
  "openai-sdk": { display: 'hidden' },
  "opencat": { display: 'hidden' },
  "openclaw": { display: 'hidden' },
  "opencode": { display: 'hidden' },
  "others": { display: 'hidden' },
  "workbuddy": { display: 'hidden' },
  "zed": { display: 'hidden' },
}
