export default {
  "index": "工具集成",
  "claude-code": "概览",
  "codex": "概览",
  "gemini-cli": "Gemini CLI 配置",
  "cursor": "Cursor 兼容性说明",
  "copilot": "GitHub Copilot 配置",
  "claude-coworks": "Claude Coworks 配置",
  "zed": "Zed Editor 接入 Look2Eye 配置指南",
  "cline": "Cline 配置",
  "openclaw": "OpenClaw",
  "cherry-studio": "Cherry Studio 配置",
  "cc-switch": "CC-Switch 配置",
  "botgem": "BotGem 配置",
  "chatbox": "Chatbox 配置",
  "workbuddy": "WorkBuddy 配置",
  "lobehub": "LobeHub 配置",
  "opencat": "OpenCat 配置",
  "nextchat": "NextChat 配置",
  "immersive-translate": "沉浸式翻译配置",
  "opencode": "OpenCode 配置",
  "openai-sdk": "OpenAI SDK 兼容",
  "langchain": "LangChain 配置",
  "llamaindex": "LlamaIndex 配置",
  "others": "其他工具集成",
}
